{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "TPU_Train_pk.ipynb",
      "provenance": [],
      "collapsed_sections": [],
      "toc_visible": true,
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "accelerator": "TPU"
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/skyloma/img2/blob/master/TPU_Train.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "4tgSMqydu-0g",
        "colab_type": "text"
      },
      "source": [
        "# 加载google云盘"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "x2PI_JcgyUdp",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "from google.colab import drive\n",
        "drive.mount('/content/drive')\n"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "l-ji808bEfQE",
        "colab_type": "text"
      },
      "source": [
        ""
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "nRZR_KbVc04J",
        "colab_type": "text"
      },
      "source": [
        "# 切换目录\n"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "cf_70f35gusB",
        "colab_type": "code",
        "cellView": "both",
        "colab": {}
      },
      "source": [
        "import os\n",
        "os.chdir(\"drive/My Drive/models_pk_rmb/models/research\")\n"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "qM2N3TVVWMR7",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "!ls"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "Nboig2LZ8I0v",
        "colab_type": "text"
      },
      "source": [
        "# 授权访问google cloud partform"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "OPld1XfVD5T9",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "from google.colab import auth\n",
        "auth.authenticate_user()\n",
        "project_id = 'dreamer8090'\n",
        "!gcloud config set project {project_id}"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "hr6YUve8XBvD",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "!gcloud auth application-default login"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "pTwN43l07mxP",
        "colab_type": "text"
      },
      "source": [
        "# 复制文件到google storage"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "567Eaq_6D5Sc",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "bucket_name=\"gs://staging.dreamer8090.appspot.com\"\n",
        "# !gsutil cp -r /content/drive/My\\ Drive/ssd_mobilenet_v1_ppn_shared_box_predictor_300x300_coco14_sync_2018_07_03/ gs://{bucket_name}/data\n",
        "!gsutil cp -r /content/drive/My\\ Drive/models_pk_rmb/models/research/data {bucket_name}\n",
        "!gsutil cp test.record  {bucket_name}/data/test.record  \n",
        "!gsutil cp train.record  {bucket_name}/data/train.record  \n",
        "# !gsutil cp pk_rmb.pbtxt gs://{bucket_name}/data/pk_rmb.pbtxt    \n"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "32tofuY1ytJl",
        "colab_type": "text"
      },
      "source": [
        "# 切换到目录research下进行训练"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "Cm9whfBQlV2p",
        "colab_type": "code",
        "outputId": "f9ef3707-733f-4106-bf02-7b5f15207cdc",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 84
        }
      },
      "source": [
        "from tensorboardcolab import TensorBoardColab\n",
        "tbc=TensorBoardColab(graph_path='gs://staging.dreamer8090.appspot.com/tpu128')"
      ],
      "execution_count": 0,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Using TensorFlow backend.\n"
          ],
          "name": "stderr"
        },
        {
          "output_type": "stream",
          "text": [
            "Wait for 8 seconds...\n",
            "TensorBoard link:\n",
            "https://29da42d8.ngrok.io\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "TfzLAHDL1vOc",
        "colab_type": "code",
        "outputId": "77a4be3f-6575-4ff4-afd7-90292678af0b",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        }
      },
      "source": [
        "!export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim; python object_detection/model_tpu_main.py \\\n",
        "--gcp_project=dreamer8090  \\\n",
        "--pipeline_config_path=tpu128.config \\\n",
        "--model_dir=gs://staging.dreamer8090.appspot.com/tpu128 \\\n",
        "--num_train_steps=100000 \\\n",
        "--num_eval_steps=8000"
      ],
      "execution_count": 33,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "WARNING:tensorflow:\n",
            "The TensorFlow contrib module will not be included in TensorFlow 2.0.\n",
            "For more information, please see:\n",
            "  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md\n",
            "  * https://github.com/tensorflow/addons\n",
            "  * https://github.com/tensorflow/io (for I/O related ops)\n",
            "If you depend on functionality not listed there, please file an issue.\n",
            "\n",
            "WARNING:tensorflow:From /content/models/research/slim/nets/inception_resnet_v2.py:373: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.\n",
            "\n",
            "WARNING:tensorflow:From /content/models/research/slim/nets/mobilenet/mobilenet.py:397: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.\n",
            "\n",
            "WARNING:tensorflow:From object_detection/model_tpu_main.py:142: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.\n",
            "\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/utils/config_util.py:102: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.\n",
            "\n",
            "W1031 09:06:10.266796 140516035643264 module_wrapper.py:139] From /content/models/research/object_detection/utils/config_util.py:102: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.\n",
            "\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/model_lib.py:628: The name tf.logging.warning is deprecated. Please use tf.compat.v1.logging.warning instead.\n",
            "\n",
            "W1031 09:06:10.273716 140516035643264 module_wrapper.py:139] From /content/models/research/object_detection/model_lib.py:628: The name tf.logging.warning is deprecated. Please use tf.compat.v1.logging.warning instead.\n",
            "\n",
            "WARNING:tensorflow:Forced number of epochs for all eval validations to be 1.\n",
            "W1031 09:06:10.273996 140516035643264 model_lib.py:629] Forced number of epochs for all eval validations to be 1.\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/utils/config_util.py:488: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.\n",
            "\n",
            "W1031 09:06:10.274173 140516035643264 module_wrapper.py:139] From /content/models/research/object_detection/utils/config_util.py:488: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.\n",
            "\n",
            "INFO:tensorflow:Maybe overwriting train_steps: 100000\n",
            "I1031 09:06:10.274305 140516035643264 config_util.py:488] Maybe overwriting train_steps: 100000\n",
            "INFO:tensorflow:Maybe overwriting use_bfloat16: False\n",
            "I1031 09:06:10.274426 140516035643264 config_util.py:488] Maybe overwriting use_bfloat16: False\n",
            "INFO:tensorflow:Maybe overwriting sample_1_of_n_eval_examples: 1\n",
            "I1031 09:06:10.274520 140516035643264 config_util.py:488] Maybe overwriting sample_1_of_n_eval_examples: 1\n",
            "INFO:tensorflow:Maybe overwriting eval_num_epochs: 1\n",
            "I1031 09:06:10.274636 140516035643264 config_util.py:488] Maybe overwriting eval_num_epochs: 1\n",
            "INFO:tensorflow:Maybe overwriting load_pretrained: True\n",
            "I1031 09:06:10.274741 140516035643264 config_util.py:488] Maybe overwriting load_pretrained: True\n",
            "INFO:tensorflow:Ignoring config override key: load_pretrained\n",
            "I1031 09:06:10.275198 140516035643264 config_util.py:498] Ignoring config override key: load_pretrained\n",
            "WARNING:tensorflow:Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.\n",
            "W1031 09:06:10.275486 140516035643264 model_lib.py:645] Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.\n",
            "INFO:tensorflow:create_estimator_and_inputs: use_tpu True, export_to_tpu False\n",
            "I1031 09:06:10.275730 140516035643264 model_lib.py:680] create_estimator_and_inputs: use_tpu True, export_to_tpu False\n",
            "INFO:tensorflow:Using config: {'_model_dir': 'gs://staging.dreamer8090.appspot.com/tpu128', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true\n",
            "graph_options {\n",
            "  rewrite_options {\n",
            "    meta_optimizer_iterations: ONE\n",
            "  }\n",
            "}\n",
            ", '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': None, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fcc307ee860>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': 'grpc://10.89.214.98:8470', '_evaluation_master': 'grpc://10.89.214.98:8470', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_tpu_config': TPUConfig(iterations_per_loop=100, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=2, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None, eval_training_input_configuration=2, experimental_host_call_every_n_steps=1), '_cluster': None}\n",
            "I1031 09:06:10.276813 140516035643264 estimator.py:212] Using config: {'_model_dir': 'gs://staging.dreamer8090.appspot.com/tpu128', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true\n",
            "graph_options {\n",
            "  rewrite_options {\n",
            "    meta_optimizer_iterations: ONE\n",
            "  }\n",
            "}\n",
            ", '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': None, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fcc307ee860>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': 'grpc://10.89.214.98:8470', '_evaluation_master': 'grpc://10.89.214.98:8470', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_tpu_config': TPUConfig(iterations_per_loop=100, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=2, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None, eval_training_input_configuration=2, experimental_host_call_every_n_steps=1), '_cluster': None}\n",
            "INFO:tensorflow:_TPUContext: eval_on_tpu False\n",
            "I1031 09:06:10.277218 140516035643264 tpu_context.py:220] _TPUContext: eval_on_tpu False\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/utils/config_util.py:188: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.\n",
            "\n",
            "W1031 09:06:11.442482 140516035643264 module_wrapper.py:139] From /content/models/research/object_detection/utils/config_util.py:188: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.\n",
            "\n",
            "INFO:tensorflow:Writing pipeline config file to gs://staging.dreamer8090.appspot.com/tpu128/pipeline.config\n",
            "I1031 09:06:11.442845 140516035643264 config_util.py:190] Writing pipeline config file to gs://staging.dreamer8090.appspot.com/tpu128/pipeline.config\n",
            "INFO:tensorflow:Querying Tensorflow master (grpc://10.89.214.98:8470) for TPU system metadata.\n",
            "I1031 09:06:12.672975 140516035643264 tpu_system_metadata.py:78] Querying Tensorflow master (grpc://10.89.214.98:8470) for TPU system metadata.\n",
            "2019-10-31 09:06:12.675936: W tensorflow/core/distributed_runtime/rpc/grpc_session.cc:370] GrpcSession::ListDevices will initialize the session with an empty graph and other defaults because the session has not yet been created.\n",
            "INFO:tensorflow:Found TPU system:\n",
            "I1031 09:06:12.682364 140516035643264 tpu_system_metadata.py:148] Found TPU system:\n",
            "INFO:tensorflow:*** Num TPU Cores: 8\n",
            "I1031 09:06:12.682642 140516035643264 tpu_system_metadata.py:149] *** Num TPU Cores: 8\n",
            "INFO:tensorflow:*** Num TPU Workers: 1\n",
            "I1031 09:06:12.682814 140516035643264 tpu_system_metadata.py:150] *** Num TPU Workers: 1\n",
            "INFO:tensorflow:*** Num TPU Cores Per Worker: 8\n",
            "I1031 09:06:12.682911 140516035643264 tpu_system_metadata.py:152] *** Num TPU Cores Per Worker: 8\n",
            "INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:CPU:0, CPU, -1, 18132923200174373972)\n",
            "I1031 09:06:12.683022 140516035643264 tpu_system_metadata.py:154] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:CPU:0, CPU, -1, 18132923200174373972)\n",
            "INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:0, TPU, 17179869184, 3102448165072722089)\n",
            "I1031 09:06:12.683902 140516035643264 tpu_system_metadata.py:154] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:0, TPU, 17179869184, 3102448165072722089)\n",
            "INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:1, TPU, 17179869184, 1077703153609051682)\n",
            "I1031 09:06:12.684013 140516035643264 tpu_system_metadata.py:154] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:1, TPU, 17179869184, 1077703153609051682)\n",
            "INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:2, TPU, 17179869184, 6036467329314715071)\n",
            "I1031 09:06:12.684113 140516035643264 tpu_system_metadata.py:154] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:2, TPU, 17179869184, 6036467329314715071)\n",
            "INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:3, TPU, 17179869184, 8346996293557643248)\n",
            "I1031 09:06:12.684199 140516035643264 tpu_system_metadata.py:154] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:3, TPU, 17179869184, 8346996293557643248)\n",
            "INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:4, TPU, 17179869184, 445820689256878810)\n",
            "I1031 09:06:12.684277 140516035643264 tpu_system_metadata.py:154] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:4, TPU, 17179869184, 445820689256878810)\n",
            "INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:5, TPU, 17179869184, 16368804617278288341)\n",
            "I1031 09:06:12.684353 140516035643264 tpu_system_metadata.py:154] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:5, TPU, 17179869184, 16368804617278288341)\n",
            "INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:6, TPU, 17179869184, 6647693080646572794)\n",
            "I1031 09:06:12.684429 140516035643264 tpu_system_metadata.py:154] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:6, TPU, 17179869184, 6647693080646572794)\n",
            "INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:7, TPU, 17179869184, 13878225431643730670)\n",
            "I1031 09:06:12.684845 140516035643264 tpu_system_metadata.py:154] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:7, TPU, 17179869184, 13878225431643730670)\n",
            "INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 8589934592, 12827303523181851239)\n",
            "I1031 09:06:12.684975 140516035643264 tpu_system_metadata.py:154] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 8589934592, 12827303523181851239)\n",
            "INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 17179869184, 3177794994953885587)\n",
            "I1031 09:06:12.685078 140516035643264 tpu_system_metadata.py:154] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 17179869184, 3177794994953885587)\n",
            "WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.\n",
            "Instructions for updating:\n",
            "If using Keras pass *_constraint arguments to layers.\n",
            "W1031 09:06:12.692904 140516035643264 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.\n",
            "Instructions for updating:\n",
            "If using Keras pass *_constraint arguments to layers.\n",
            "WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.\n",
            "Instructions for updating:\n",
            "Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.\n",
            "W1031 09:06:12.693491 140516035643264 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.\n",
            "Instructions for updating:\n",
            "Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "I1031 09:06:12.707838 140516035643264 estimator.py:1148] Calling model_fn.\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/data_decoders/tf_example_decoder.py:182: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.\n",
            "\n",
            "W1031 09:06:12.711758 140516035643264 module_wrapper.py:139] From /content/models/research/object_detection/data_decoders/tf_example_decoder.py:182: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.\n",
            "\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/data_decoders/tf_example_decoder.py:197: The name tf.VarLenFeature is deprecated. Please use tf.io.VarLenFeature instead.\n",
            "\n",
            "W1031 09:06:12.712048 140516035643264 module_wrapper.py:139] From /content/models/research/object_detection/data_decoders/tf_example_decoder.py:197: The name tf.VarLenFeature is deprecated. Please use tf.io.VarLenFeature instead.\n",
            "\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/builders/dataset_builder.py:64: The name tf.gfile.Glob is deprecated. Please use tf.io.gfile.glob instead.\n",
            "\n",
            "W1031 09:06:13.077584 140516035643264 module_wrapper.py:139] From /content/models/research/object_detection/builders/dataset_builder.py:64: The name tf.gfile.Glob is deprecated. Please use tf.io.gfile.glob instead.\n",
            "\n",
            "WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.\n",
            "W1031 09:06:13.126737 140516035643264 dataset_builder.py:72] num_readers has been reduced to 1 to match input file shards.\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/builders/dataset_builder.py:86: parallel_interleave (from tensorflow.contrib.data.python.ops.interleave_ops) is deprecated and will be removed in a future version.\n",
            "Instructions for updating:\n",
            "Use `tf.data.experimental.parallel_interleave(...)`.\n",
            "W1031 09:06:13.135022 140516035643264 deprecation.py:323] From /content/models/research/object_detection/builders/dataset_builder.py:86: parallel_interleave (from tensorflow.contrib.data.python.ops.interleave_ops) is deprecated and will be removed in a future version.\n",
            "Instructions for updating:\n",
            "Use `tf.data.experimental.parallel_interleave(...)`.\n",
            "WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/data/python/ops/interleave_ops.py:77: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.\n",
            "Instructions for updating:\n",
            "Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_determinstic`.\n",
            "W1031 09:06:13.135384 140516035643264 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/data/python/ops/interleave_ops.py:77: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.\n",
            "Instructions for updating:\n",
            "Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_determinstic`.\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/builders/dataset_builder.py:155: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.\n",
            "Instructions for updating:\n",
            "Use `tf.data.Dataset.map()\n",
            "W1031 09:06:13.165445 140516035643264 deprecation.py:323] From /content/models/research/object_detection/builders/dataset_builder.py:155: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.\n",
            "Instructions for updating:\n",
            "Use `tf.data.Dataset.map()\n",
            "WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.logging.warn is deprecated. Please use tf.compat.v1.logging.warn instead.\n",
            "\n",
            "W1031 09:06:14.696419 140516035643264 module_wrapper.py:139] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.logging.warn is deprecated. Please use tf.compat.v1.logging.warn instead.\n",
            "\n",
            "WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.is_nan is deprecated. Please use tf.math.is_nan instead.\n",
            "\n",
            "W1031 09:06:22.292829 140516035643264 module_wrapper.py:139] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.is_nan is deprecated. Please use tf.math.is_nan instead.\n",
            "\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/utils/ops.py:493: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.\n",
            "Instructions for updating:\n",
            "Use tf.where in 2.0, which has the same broadcast rule as np.where\n",
            "W1031 09:06:22.379481 140516035643264 deprecation.py:323] From /content/models/research/object_detection/utils/ops.py:493: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.\n",
            "Instructions for updating:\n",
            "Use tf.where in 2.0, which has the same broadcast rule as np.where\n",
            "WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.\n",
            "\n",
            "W1031 09:06:25.053582 140516035643264 module_wrapper.py:139] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.\n",
            "\n",
            "WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/operators/control_flow.py:1004: sample_distorted_bounding_box (from tensorflow.python.ops.image_ops_impl) is deprecated and will be removed in a future version.\n",
            "Instructions for updating:\n",
            "`seed2` arg is deprecated.Use sample_distorted_bounding_box_v2 instead.\n",
            "W1031 09:06:28.786950 140516035643264 api.py:332] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/operators/control_flow.py:1004: sample_distorted_bounding_box (from tensorflow.python.ops.image_ops_impl) is deprecated and will be removed in a future version.\n",
            "Instructions for updating:\n",
            "`seed2` arg is deprecated.Use sample_distorted_bounding_box_v2 instead.\n",
            "WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.image.resize_images is deprecated. Please use tf.image.resize instead.\n",
            "\n",
            "W1031 09:06:32.410371 140516035643264 module_wrapper.py:139] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.image.resize_images is deprecated. Please use tf.image.resize instead.\n",
            "\n",
            "WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.image.resize_nearest_neighbor is deprecated. Please use tf.compat.v1.image.resize_nearest_neighbor instead.\n",
            "\n",
            "W1031 09:06:32.411589 140516035643264 module_wrapper.py:139] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.image.resize_nearest_neighbor is deprecated. Please use tf.compat.v1.image.resize_nearest_neighbor instead.\n",
            "\n",
            "WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.string_to_hash_bucket_fast is deprecated. Please use tf.strings.to_hash_bucket_fast instead.\n",
            "\n",
            "W1031 09:06:34.646641 140516035643264 module_wrapper.py:139] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.string_to_hash_bucket_fast is deprecated. Please use tf.strings.to_hash_bucket_fast instead.\n",
            "\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/builders/dataset_builder.py:158: batch_and_drop_remainder (from tensorflow.contrib.data.python.ops.batching) is deprecated and will be removed in a future version.\n",
            "Instructions for updating:\n",
            "Use `tf.data.Dataset.batch(..., drop_remainder=True)`.\n",
            "W1031 09:06:35.163183 140516035643264 deprecation.py:323] From /content/models/research/object_detection/builders/dataset_builder.py:158: batch_and_drop_remainder (from tensorflow.contrib.data.python.ops.batching) is deprecated and will be removed in a future version.\n",
            "Instructions for updating:\n",
            "Use `tf.data.Dataset.batch(..., drop_remainder=True)`.\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/meta_architectures/ssd_meta_arch.py:595: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.\n",
            "\n",
            "W1031 09:06:35.261025 140516035643264 module_wrapper.py:139] From /content/models/research/object_detection/meta_architectures/ssd_meta_arch.py:595: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.\n",
            "\n",
            "WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/layers/python/layers/layers.py:1057: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.\n",
            "Instructions for updating:\n",
            "Please use `layer.__call__` method instead.\n",
            "W1031 09:06:35.263755 140516035643264 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/layers/python/layers/layers.py:1057: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.\n",
            "Instructions for updating:\n",
            "Please use `layer.__call__` method instead.\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/core/anchor_generator.py:171: The name tf.assert_equal is deprecated. Please use tf.compat.v1.assert_equal instead.\n",
            "\n",
            "W1031 09:06:38.119841 140516035643264 module_wrapper.py:139] From /content/models/research/object_detection/core/anchor_generator.py:171: The name tf.assert_equal is deprecated. Please use tf.compat.v1.assert_equal instead.\n",
            "\n",
            "INFO:tensorflow:depth of additional conv before box predictor: 0\n",
            "I1031 09:06:38.135019 140516035643264 convolutional_box_predictor.py:151] depth of additional conv before box predictor: 0\n",
            "INFO:tensorflow:depth of additional conv before box predictor: 0\n",
            "I1031 09:06:38.182452 140516035643264 convolutional_box_predictor.py:151] depth of additional conv before box predictor: 0\n",
            "INFO:tensorflow:depth of additional conv before box predictor: 0\n",
            "I1031 09:06:38.230465 140516035643264 convolutional_box_predictor.py:151] depth of additional conv before box predictor: 0\n",
            "INFO:tensorflow:depth of additional conv before box predictor: 0\n",
            "I1031 09:06:38.283278 140516035643264 convolutional_box_predictor.py:151] depth of additional conv before box predictor: 0\n",
            "INFO:tensorflow:depth of additional conv before box predictor: 0\n",
            "I1031 09:06:38.334084 140516035643264 convolutional_box_predictor.py:151] depth of additional conv before box predictor: 0\n",
            "INFO:tensorflow:depth of additional conv before box predictor: 0\n",
            "I1031 09:06:38.395447 140516035643264 convolutional_box_predictor.py:151] depth of additional conv before box predictor: 0\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/utils/variables_helper.py:179: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.\n",
            "\n",
            "W1031 09:06:38.454466 140516035643264 module_wrapper.py:139] From /content/models/research/object_detection/utils/variables_helper.py:179: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.\n",
            "\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/utils/variables_helper.py:139: The name tf.train.NewCheckpointReader is deprecated. Please use tf.compat.v1.train.NewCheckpointReader instead.\n",
            "\n",
            "W1031 09:06:38.456000 140516035643264 module_wrapper.py:139] From /content/models/research/object_detection/utils/variables_helper.py:139: The name tf.train.NewCheckpointReader is deprecated. Please use tf.compat.v1.train.NewCheckpointReader instead.\n",
            "\n",
            "W1031 09:06:38.778190 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_0/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.778526 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_0/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.778624 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_0/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.778711 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_0/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.778870 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_0/weights] is not available in checkpoint\n",
            "W1031 09:06:38.778955 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_10_depthwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.779040 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_10_depthwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.779157 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_10_depthwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.779251 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_10_depthwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.779327 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_10_depthwise/depthwise_weights] is not available in checkpoint\n",
            "W1031 09:06:38.779419 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_10_pointwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.779524 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_10_pointwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.779613 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_10_pointwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.779714 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_10_pointwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.779792 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_10_pointwise/weights] is not available in checkpoint\n",
            "W1031 09:06:38.779859 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_11_depthwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.779934 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_11_depthwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.780019 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_11_depthwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.780106 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_11_depthwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.780177 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_11_depthwise/depthwise_weights] is not available in checkpoint\n",
            "W1031 09:06:38.780255 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_11_pointwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.780339 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_11_pointwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.780426 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_11_pointwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.780514 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_11_pointwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.780586 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_11_pointwise/weights] is not available in checkpoint\n",
            "W1031 09:06:38.780649 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_12_depthwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.780740 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_12_depthwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.780827 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_12_depthwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.780919 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_12_depthwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.780989 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_12_depthwise/depthwise_weights] is not available in checkpoint\n",
            "W1031 09:06:38.781068 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_12_pointwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.781151 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_12_pointwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.781235 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_12_pointwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.781318 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_12_pointwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.781399 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_12_pointwise/weights] is not available in checkpoint\n",
            "W1031 09:06:38.781467 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_depthwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.781548 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_depthwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.781634 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_depthwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.781736 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_depthwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.781809 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_depthwise/depthwise_weights] is not available in checkpoint\n",
            "W1031 09:06:38.781897 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.781981 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.782067 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.782154 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.782226 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise/weights] is not available in checkpoint\n",
            "W1031 09:06:38.782287 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_1_Conv2d_2_1x1_256/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.782370 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_1_Conv2d_2_1x1_256/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.782456 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_1_Conv2d_2_1x1_256/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.782543 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_1_Conv2d_2_1x1_256/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.782628 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_1_Conv2d_2_1x1_256/weights] is not available in checkpoint\n",
            "W1031 09:06:38.782713 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_1_Conv2d_3_1x1_128/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.782794 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_1_Conv2d_3_1x1_128/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.782883 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_1_Conv2d_3_1x1_128/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.782967 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_1_Conv2d_3_1x1_128/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.783051 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_1_Conv2d_3_1x1_128/weights] is not available in checkpoint\n",
            "W1031 09:06:38.783117 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_1_Conv2d_4_1x1_128/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.783198 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_1_Conv2d_4_1x1_128/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.783281 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_1_Conv2d_4_1x1_128/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.783365 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_1_Conv2d_4_1x1_128/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.783451 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_1_Conv2d_4_1x1_128/weights] is not available in checkpoint\n",
            "W1031 09:06:38.783519 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_1_Conv2d_5_1x1_64/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.783599 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_1_Conv2d_5_1x1_64/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.783697 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_1_Conv2d_5_1x1_64/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.783784 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_1_Conv2d_5_1x1_64/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.783874 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_1_Conv2d_5_1x1_64/weights] is not available in checkpoint\n",
            "W1031 09:06:38.783946 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_2_Conv2d_2_3x3_s2_512/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.784028 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_2_Conv2d_2_3x3_s2_512/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.784112 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_2_Conv2d_2_3x3_s2_512/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.784198 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_2_Conv2d_2_3x3_s2_512/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.784275 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_2_Conv2d_2_3x3_s2_512/weights] is not available in checkpoint\n",
            "W1031 09:06:38.784337 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_2_Conv2d_3_3x3_s2_256/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.784421 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_2_Conv2d_3_3x3_s2_256/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.784507 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_2_Conv2d_3_3x3_s2_256/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.784591 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_2_Conv2d_3_3x3_s2_256/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.784675 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_2_Conv2d_3_3x3_s2_256/weights] is not available in checkpoint\n",
            "W1031 09:06:38.784736 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_2_Conv2d_4_3x3_s2_256/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.784816 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_2_Conv2d_4_3x3_s2_256/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.784906 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_2_Conv2d_4_3x3_s2_256/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.784994 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_2_Conv2d_4_3x3_s2_256/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.785061 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_2_Conv2d_4_3x3_s2_256/weights] is not available in checkpoint\n",
            "W1031 09:06:38.785122 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_2_Conv2d_5_3x3_s2_128/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.785201 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_2_Conv2d_5_3x3_s2_128/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.785285 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_2_Conv2d_5_3x3_s2_128/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.785370 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_2_Conv2d_5_3x3_s2_128/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.785439 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_13_pointwise_2_Conv2d_5_3x3_s2_128/weights] is not available in checkpoint\n",
            "W1031 09:06:38.785500 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_1_depthwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.785560 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_1_depthwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.785636 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_1_depthwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.785736 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_1_depthwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.785810 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_1_depthwise/depthwise_weights] is not available in checkpoint\n",
            "W1031 09:06:38.785898 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_1_pointwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.785967 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_1_pointwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.786045 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_1_pointwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.786127 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_1_pointwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.786199 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_1_pointwise/weights] is not available in checkpoint\n",
            "W1031 09:06:38.786261 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_2_depthwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.786319 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_2_depthwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.786397 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_2_depthwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.786484 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_2_depthwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.786555 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_2_depthwise/depthwise_weights] is not available in checkpoint\n",
            "W1031 09:06:38.786634 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_2_pointwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.786715 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_2_pointwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.786791 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_2_pointwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.786879 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_2_pointwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.786950 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_2_pointwise/weights] is not available in checkpoint\n",
            "W1031 09:06:38.787011 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_3_depthwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.793128 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_3_depthwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.793423 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_3_depthwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.793557 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_3_depthwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.793650 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_3_depthwise/depthwise_weights] is not available in checkpoint\n",
            "W1031 09:06:38.793786 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_3_pointwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.793883 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_3_pointwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.793974 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_3_pointwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.794074 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_3_pointwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.794156 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_3_pointwise/weights] is not available in checkpoint\n",
            "W1031 09:06:38.794226 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_4_depthwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.794301 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_4_depthwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.794407 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_4_depthwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.794510 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_4_depthwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.794592 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_4_depthwise/depthwise_weights] is not available in checkpoint\n",
            "W1031 09:06:38.794704 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_4_pointwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.794794 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_4_pointwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.794891 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_4_pointwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.794996 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_4_pointwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.795079 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_4_pointwise/weights] is not available in checkpoint\n",
            "W1031 09:06:38.795156 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_5_depthwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.795235 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_5_depthwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.795345 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_5_depthwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.795457 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_5_depthwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.795549 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_5_depthwise/depthwise_weights] is not available in checkpoint\n",
            "W1031 09:06:38.795649 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_5_pointwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.795755 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_5_pointwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.795855 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_5_pointwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.795966 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_5_pointwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.796058 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_5_pointwise/weights] is not available in checkpoint\n",
            "W1031 09:06:38.796140 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_6_depthwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.796218 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_6_depthwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.796321 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_6_depthwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.796449 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_6_depthwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.796542 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_6_depthwise/depthwise_weights] is not available in checkpoint\n",
            "W1031 09:06:38.796644 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_6_pointwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.796751 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_6_pointwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.796855 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_6_pointwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.796966 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_6_pointwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.797057 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_6_pointwise/weights] is not available in checkpoint\n",
            "W1031 09:06:38.797138 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_7_depthwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.797212 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_7_depthwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.797315 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_7_depthwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.797438 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_7_depthwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.797529 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_7_depthwise/depthwise_weights] is not available in checkpoint\n",
            "W1031 09:06:38.797635 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_7_pointwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.797958 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_7_pointwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.798083 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_7_pointwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.798201 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_7_pointwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.798296 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_7_pointwise/weights] is not available in checkpoint\n",
            "W1031 09:06:38.798391 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_8_depthwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.798474 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_8_depthwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.798578 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_8_depthwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.798708 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_8_depthwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.798804 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_8_depthwise/depthwise_weights] is not available in checkpoint\n",
            "W1031 09:06:38.798912 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_8_pointwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.799005 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_8_pointwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.799108 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_8_pointwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.799219 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_8_pointwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.799317 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_8_pointwise/weights] is not available in checkpoint\n",
            "W1031 09:06:38.799407 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_9_depthwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.799508 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_9_depthwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.799610 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_9_depthwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.799743 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_9_depthwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.799837 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_9_depthwise/depthwise_weights] is not available in checkpoint\n",
            "W1031 09:06:38.799943 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_9_pointwise/BatchNorm/beta] is not available in checkpoint\n",
            "W1031 09:06:38.800033 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_9_pointwise/BatchNorm/gamma] is not available in checkpoint\n",
            "W1031 09:06:38.800135 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_9_pointwise/BatchNorm/moving_mean] is not available in checkpoint\n",
            "W1031 09:06:38.800245 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_9_pointwise/BatchNorm/moving_variance] is not available in checkpoint\n",
            "W1031 09:06:38.800342 140516035643264 variables_helper.py:157] Variable [MobilenetV1/Conv2d_9_pointwise/weights] is not available in checkpoint\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/box_coders/faster_rcnn_box_coder.py:82: The name tf.log is deprecated. Please use tf.math.log instead.\n",
            "\n",
            "W1031 09:06:38.973408 140516035643264 module_wrapper.py:139] From /content/models/research/object_detection/box_coders/faster_rcnn_box_coder.py:82: The name tf.log is deprecated. Please use tf.math.log instead.\n",
            "\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/core/losses.py:177: The name tf.losses.huber_loss is deprecated. Please use tf.compat.v1.losses.huber_loss instead.\n",
            "\n",
            "W1031 09:06:45.583367 140516035643264 module_wrapper.py:139] From /content/models/research/object_detection/core/losses.py:177: The name tf.losses.huber_loss is deprecated. Please use tf.compat.v1.losses.huber_loss instead.\n",
            "\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/core/losses.py:183: The name tf.losses.Reduction is deprecated. Please use tf.compat.v1.losses.Reduction instead.\n",
            "\n",
            "W1031 09:06:45.585402 140516035643264 module_wrapper.py:139] From /content/models/research/object_detection/core/losses.py:183: The name tf.losses.Reduction is deprecated. Please use tf.compat.v1.losses.Reduction instead.\n",
            "\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/meta_architectures/ssd_meta_arch.py:1266: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.\n",
            "\n",
            "W1031 09:06:45.637488 140516035643264 module_wrapper.py:139] From /content/models/research/object_detection/meta_architectures/ssd_meta_arch.py:1266: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.\n",
            "\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/builders/graph_rewriter_builder.py:36: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.\n",
            "\n",
            "W1031 09:06:45.654579 140516035643264 module_wrapper.py:139] From /content/models/research/object_detection/builders/graph_rewriter_builder.py:36: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.\n",
            "\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/add_fold\n",
            "I1031 09:06:54.087713 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_depthwise/add_fold\n",
            "I1031 09:06:54.088358 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_depthwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_pointwise/add_fold\n",
            "I1031 09:06:54.088760 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_pointwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_2_depthwise/add_fold\n",
            "I1031 09:06:54.089134 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_2_depthwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_2_pointwise/add_fold\n",
            "I1031 09:06:54.089480 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_2_pointwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_3_depthwise/add_fold\n",
            "I1031 09:06:54.089852 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_3_depthwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_3_pointwise/add_fold\n",
            "I1031 09:06:54.090204 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_3_pointwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_4_depthwise/add_fold\n",
            "I1031 09:06:54.090611 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_4_depthwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_4_pointwise/add_fold\n",
            "I1031 09:06:54.090983 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_4_pointwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_5_depthwise/add_fold\n",
            "I1031 09:06:54.091351 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_5_depthwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_5_pointwise/add_fold\n",
            "I1031 09:06:54.091714 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_5_pointwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_6_depthwise/add_fold\n",
            "I1031 09:06:54.092084 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_6_depthwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_6_pointwise/add_fold\n",
            "I1031 09:06:54.092432 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_6_pointwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_7_depthwise/add_fold\n",
            "I1031 09:06:54.092824 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_7_depthwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_7_pointwise/add_fold\n",
            "I1031 09:06:54.093196 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_7_pointwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_8_depthwise/add_fold\n",
            "I1031 09:06:54.093556 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_8_depthwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_8_pointwise/add_fold\n",
            "I1031 09:06:54.094014 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_8_pointwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_9_depthwise/add_fold\n",
            "I1031 09:06:54.094411 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_9_depthwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_9_pointwise/add_fold\n",
            "I1031 09:06:54.094782 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_9_pointwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_10_depthwise/add_fold\n",
            "I1031 09:06:54.095151 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_10_depthwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_10_pointwise/add_fold\n",
            "I1031 09:06:54.095503 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_10_pointwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_11_depthwise/add_fold\n",
            "I1031 09:06:54.095892 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_11_depthwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_11_pointwise/add_fold\n",
            "I1031 09:06:54.096261 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_11_pointwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_12_depthwise/add_fold\n",
            "I1031 09:06:54.096623 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_12_depthwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_12_pointwise/add_fold\n",
            "I1031 09:06:54.096990 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_12_pointwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_13_depthwise/add_fold\n",
            "I1031 09:06:54.097354 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_13_depthwise/add_fold\n",
            "INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_13_pointwise/add_fold\n",
            "I1031 09:06:54.097714 140516035643264 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_13_pointwise/add_fold\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/model_lib.py:380: The name tf.train.get_or_create_global_step is deprecated. Please use tf.compat.v1.train.get_or_create_global_step instead.\n",
            "\n",
            "W1031 09:06:54.114578 140516035643264 module_wrapper.py:139] From /content/models/research/object_detection/model_lib.py:380: The name tf.train.get_or_create_global_step is deprecated. Please use tf.compat.v1.train.get_or_create_global_step instead.\n",
            "\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/builders/optimizer_builder.py:58: The name tf.train.MomentumOptimizer is deprecated. Please use tf.compat.v1.train.MomentumOptimizer instead.\n",
            "\n",
            "W1031 09:06:54.136840 140516035643264 module_wrapper.py:139] From /content/models/research/object_detection/builders/optimizer_builder.py:58: The name tf.train.MomentumOptimizer is deprecated. Please use tf.compat.v1.train.MomentumOptimizer instead.\n",
            "\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/model_lib.py:398: The name tf.trainable_variables is deprecated. Please use tf.compat.v1.trainable_variables instead.\n",
            "\n",
            "W1031 09:06:54.137343 140516035643264 module_wrapper.py:139] From /content/models/research/object_detection/model_lib.py:398: The name tf.trainable_variables is deprecated. Please use tf.compat.v1.trainable_variables instead.\n",
            "\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/model_lib.py:347: The name tf.train.init_from_checkpoint is deprecated. Please use tf.compat.v1.train.init_from_checkpoint instead.\n",
            "\n",
            "W1031 09:07:02.647069 140516035643264 module_wrapper.py:139] From /content/models/research/object_detection/model_lib.py:347: The name tf.train.init_from_checkpoint is deprecated. Please use tf.compat.v1.train.init_from_checkpoint instead.\n",
            "\n",
            "WARNING:tensorflow:From /content/models/research/object_detection/model_lib.py:349: The name tf.train.Scaffold is deprecated. Please use tf.compat.v1.train.Scaffold instead.\n",
            "\n",
            "W1031 09:07:03.164605 140516035643264 module_wrapper.py:139] From /content/models/research/object_detection/model_lib.py:349: The name tf.train.Scaffold is deprecated. Please use tf.compat.v1.train.Scaffold instead.\n",
            "\n",
            "INFO:tensorflow:Create CheckpointSaverHook.\n",
            "I1031 09:07:04.180784 140516035643264 basic_session_run_hooks.py:541] Create CheckpointSaverHook.\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "I1031 09:07:04.423330 140516035643264 estimator.py:1150] Done calling model_fn.\n",
            "INFO:tensorflow:TPU job name tpu_worker\n",
            "I1031 09:07:08.700826 140516035643264 tpu_estimator.py:506] TPU job name tpu_worker\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "I1031 09:07:10.697436 140516035643264 monitored_session.py:240] Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from gs://staging.dreamer8090.appspot.com/tpu128/model.ckpt-60000\n",
            "I1031 09:07:10.865542 140516035643264 saver.py:1284] Restoring parameters from gs://staging.dreamer8090.appspot.com/tpu128/model.ckpt-60000\n",
            "ERROR:tensorflow:Error recorded from training_loop: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:\n",
            "\n",
            "From /job:tpu_worker/replica:0/task:0:\n",
            "Unsuccessful TensorSliceReader constructor: Failed to get matching files on gs://staging.dreamer8090.appspot.com/tpu128/model.ckpt-60000: Permission denied: Error executing an HTTP request: HTTP response code 403 with body '{\n",
            "  \"error\": {\n",
            "    \"code\": 403,\n",
            "    \"message\": \"service-495559152420@cloud-tpu.iam.gserviceaccount.com does not have storage.objects.list access to staging.dreamer8090.appspot.com.\",\n",
            "    \"errors\": [\n",
            "      {\n",
            "        \"message\": \"service-495559152420@cloud-tpu.iam.gserviceaccount.com does not have storage.objects.list access to staging.dreamer8090.appspot.com.\",\n",
            "        \"domain\": \"global\",\n",
            "        \"reason\": \"forbidden\"\n",
            "      }\n",
            "    ]\n",
            "  }\n",
            "}\n",
            "'\n",
            "\t when reading gs://staging.dreamer8090.appspot.com/tpu128\n",
            "\t [[node save/RestoreV2 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]\n",
            "\n",
            "Original stack trace for 'save/RestoreV2':\n",
            "  File \"object_detection/model_tpu_main.py\", line 142, in <module>\n",
            "    tf.app.run()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py\", line 40, in run\n",
            "    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/absl/app.py\", line 299, in run\n",
            "    _run_main(main, args)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/absl/app.py\", line 250, in _run_main\n",
            "    sys.exit(main(argv))\n",
            "  File \"object_detection/model_tpu_main.py\", line 126, in main\n",
            "    estimator.train(input_fn=train_input_fn, max_steps=train_steps)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py\", line 3030, in train\n",
            "    saving_listeners=saving_listeners)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py\", line 370, in train\n",
            "    loss = self._train_model(input_fn, hooks, saving_listeners)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py\", line 1161, in _train_model\n",
            "    return self._train_model_default(input_fn, hooks, saving_listeners)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py\", line 1195, in _train_model_default\n",
            "    saving_listeners)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py\", line 1490, in _train_with_estimator_spec\n",
            "    log_step_count_steps=log_step_count_steps) as mon_sess:\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 584, in MonitoredTrainingSession\n",
            "    stop_grace_period_secs=stop_grace_period_secs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 1014, in __init__\n",
            "    stop_grace_period_secs=stop_grace_period_secs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 725, in __init__\n",
            "    self._sess = _RecoverableSession(self._coordinated_creator)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 1207, in __init__\n",
            "    _WrappedSession.__init__(self, self._create_session())\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 1212, in _create_session\n",
            "    return self._sess_creator.create_session()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 878, in create_session\n",
            "    self.tf_sess = self._session_creator.create_session()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 638, in create_session\n",
            "    self._scaffold.finalize()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py\", line 3761, in _finalize\n",
            "    wrapped_finalize()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 237, in finalize\n",
            "    self._saver.build()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 840, in build\n",
            "    self._build(self._filename, build_save=True, build_restore=True)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 878, in _build\n",
            "    build_restore=build_restore)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 502, in _build_internal\n",
            "    restore_sequentially, reshape)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 381, in _AddShardedRestoreOps\n",
            "    name=\"restore_shard\"))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 328, in _AddRestoreOps\n",
            "    restore_sequentially)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 575, in bulk_restore\n",
            "    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_io_ops.py\", line 1696, in restore_v2\n",
            "    name=name)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py\", line 794, in _apply_op_helper\n",
            "    op_def=op_def)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py\", line 507, in new_func\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py\", line 3357, in create_op\n",
            "    attrs, op_def, compute_device)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py\", line 3426, in _create_op_internal\n",
            "    op_def=op_def)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py\", line 1748, in __init__\n",
            "    self._traceback = tf_stack.extract_stack()\n",
            "\n",
            "E1031 09:07:19.490992 140516035643264 error_handling.py:75] Error recorded from training_loop: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:\n",
            "\n",
            "From /job:tpu_worker/replica:0/task:0:\n",
            "Unsuccessful TensorSliceReader constructor: Failed to get matching files on gs://staging.dreamer8090.appspot.com/tpu128/model.ckpt-60000: Permission denied: Error executing an HTTP request: HTTP response code 403 with body '{\n",
            "  \"error\": {\n",
            "    \"code\": 403,\n",
            "    \"message\": \"service-495559152420@cloud-tpu.iam.gserviceaccount.com does not have storage.objects.list access to staging.dreamer8090.appspot.com.\",\n",
            "    \"errors\": [\n",
            "      {\n",
            "        \"message\": \"service-495559152420@cloud-tpu.iam.gserviceaccount.com does not have storage.objects.list access to staging.dreamer8090.appspot.com.\",\n",
            "        \"domain\": \"global\",\n",
            "        \"reason\": \"forbidden\"\n",
            "      }\n",
            "    ]\n",
            "  }\n",
            "}\n",
            "'\n",
            "\t when reading gs://staging.dreamer8090.appspot.com/tpu128\n",
            "\t [[node save/RestoreV2 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]\n",
            "\n",
            "Original stack trace for 'save/RestoreV2':\n",
            "  File \"object_detection/model_tpu_main.py\", line 142, in <module>\n",
            "    tf.app.run()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py\", line 40, in run\n",
            "    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/absl/app.py\", line 299, in run\n",
            "    _run_main(main, args)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/absl/app.py\", line 250, in _run_main\n",
            "    sys.exit(main(argv))\n",
            "  File \"object_detection/model_tpu_main.py\", line 126, in main\n",
            "    estimator.train(input_fn=train_input_fn, max_steps=train_steps)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py\", line 3030, in train\n",
            "    saving_listeners=saving_listeners)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py\", line 370, in train\n",
            "    loss = self._train_model(input_fn, hooks, saving_listeners)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py\", line 1161, in _train_model\n",
            "    return self._train_model_default(input_fn, hooks, saving_listeners)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py\", line 1195, in _train_model_default\n",
            "    saving_listeners)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py\", line 1490, in _train_with_estimator_spec\n",
            "    log_step_count_steps=log_step_count_steps) as mon_sess:\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 584, in MonitoredTrainingSession\n",
            "    stop_grace_period_secs=stop_grace_period_secs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 1014, in __init__\n",
            "    stop_grace_period_secs=stop_grace_period_secs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 725, in __init__\n",
            "    self._sess = _RecoverableSession(self._coordinated_creator)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 1207, in __init__\n",
            "    _WrappedSession.__init__(self, self._create_session())\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 1212, in _create_session\n",
            "    return self._sess_creator.create_session()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 878, in create_session\n",
            "    self.tf_sess = self._session_creator.create_session()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 638, in create_session\n",
            "    self._scaffold.finalize()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py\", line 3761, in _finalize\n",
            "    wrapped_finalize()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 237, in finalize\n",
            "    self._saver.build()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 840, in build\n",
            "    self._build(self._filename, build_save=True, build_restore=True)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 878, in _build\n",
            "    build_restore=build_restore)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 502, in _build_internal\n",
            "    restore_sequentially, reshape)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 381, in _AddShardedRestoreOps\n",
            "    name=\"restore_shard\"))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 328, in _AddRestoreOps\n",
            "    restore_sequentially)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 575, in bulk_restore\n",
            "    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_io_ops.py\", line 1696, in restore_v2\n",
            "    name=name)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py\", line 794, in _apply_op_helper\n",
            "    op_def=op_def)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py\", line 507, in new_func\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py\", line 3357, in create_op\n",
            "    attrs, op_def, compute_device)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py\", line 3426, in _create_op_internal\n",
            "    op_def=op_def)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py\", line 1748, in __init__\n",
            "    self._traceback = tf_stack.extract_stack()\n",
            "\n",
            "INFO:tensorflow:training_loop marked as finished\n",
            "I1031 09:07:19.576767 140516035643264 error_handling.py:101] training_loop marked as finished\n",
            "WARNING:tensorflow:Reraising captured error\n",
            "W1031 09:07:19.577055 140516035643264 error_handling.py:135] Reraising captured error\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py\", line 1365, in _do_call\n",
            "    return fn(*args)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py\", line 1350, in _run_fn\n",
            "    target_list, run_metadata)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py\", line 1443, in _call_tf_sessionrun\n",
            "    run_metadata)\n",
            "tensorflow.python.framework.errors_impl.InvalidArgumentError: From /job:tpu_worker/replica:0/task:0:\n",
            "Unsuccessful TensorSliceReader constructor: Failed to get matching files on gs://staging.dreamer8090.appspot.com/tpu128/model.ckpt-60000: Permission denied: Error executing an HTTP request: HTTP response code 403 with body '{\n",
            "  \"error\": {\n",
            "    \"code\": 403,\n",
            "    \"message\": \"service-495559152420@cloud-tpu.iam.gserviceaccount.com does not have storage.objects.list access to staging.dreamer8090.appspot.com.\",\n",
            "    \"errors\": [\n",
            "      {\n",
            "        \"message\": \"service-495559152420@cloud-tpu.iam.gserviceaccount.com does not have storage.objects.list access to staging.dreamer8090.appspot.com.\",\n",
            "        \"domain\": \"global\",\n",
            "        \"reason\": \"forbidden\"\n",
            "      }\n",
            "    ]\n",
            "  }\n",
            "}\n",
            "'\n",
            "\t when reading gs://staging.dreamer8090.appspot.com/tpu128\n",
            "\t [[{{node save/RestoreV2}}]]\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 1290, in restore\n",
            "    {self.saver_def.filename_tensor_name: save_path})\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py\", line 956, in run\n",
            "    run_metadata_ptr)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py\", line 1180, in _run\n",
            "    feed_dict_tensor, options, run_metadata)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py\", line 1359, in _do_run\n",
            "    run_metadata)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py\", line 1384, in _do_call\n",
            "    raise type(e)(node_def, op, message)\n",
            "tensorflow.python.framework.errors_impl.InvalidArgumentError: From /job:tpu_worker/replica:0/task:0:\n",
            "Unsuccessful TensorSliceReader constructor: Failed to get matching files on gs://staging.dreamer8090.appspot.com/tpu128/model.ckpt-60000: Permission denied: Error executing an HTTP request: HTTP response code 403 with body '{\n",
            "  \"error\": {\n",
            "    \"code\": 403,\n",
            "    \"message\": \"service-495559152420@cloud-tpu.iam.gserviceaccount.com does not have storage.objects.list access to staging.dreamer8090.appspot.com.\",\n",
            "    \"errors\": [\n",
            "      {\n",
            "        \"message\": \"service-495559152420@cloud-tpu.iam.gserviceaccount.com does not have storage.objects.list access to staging.dreamer8090.appspot.com.\",\n",
            "        \"domain\": \"global\",\n",
            "        \"reason\": \"forbidden\"\n",
            "      }\n",
            "    ]\n",
            "  }\n",
            "}\n",
            "'\n",
            "\t when reading gs://staging.dreamer8090.appspot.com/tpu128\n",
            "\t [[node save/RestoreV2 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]\n",
            "\n",
            "Original stack trace for 'save/RestoreV2':\n",
            "  File \"object_detection/model_tpu_main.py\", line 142, in <module>\n",
            "    tf.app.run()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py\", line 40, in run\n",
            "    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/absl/app.py\", line 299, in run\n",
            "    _run_main(main, args)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/absl/app.py\", line 250, in _run_main\n",
            "    sys.exit(main(argv))\n",
            "  File \"object_detection/model_tpu_main.py\", line 126, in main\n",
            "    estimator.train(input_fn=train_input_fn, max_steps=train_steps)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py\", line 3030, in train\n",
            "    saving_listeners=saving_listeners)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py\", line 370, in train\n",
            "    loss = self._train_model(input_fn, hooks, saving_listeners)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py\", line 1161, in _train_model\n",
            "    return self._train_model_default(input_fn, hooks, saving_listeners)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py\", line 1195, in _train_model_default\n",
            "    saving_listeners)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py\", line 1490, in _train_with_estimator_spec\n",
            "    log_step_count_steps=log_step_count_steps) as mon_sess:\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 584, in MonitoredTrainingSession\n",
            "    stop_grace_period_secs=stop_grace_period_secs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 1014, in __init__\n",
            "    stop_grace_period_secs=stop_grace_period_secs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 725, in __init__\n",
            "    self._sess = _RecoverableSession(self._coordinated_creator)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 1207, in __init__\n",
            "    _WrappedSession.__init__(self, self._create_session())\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 1212, in _create_session\n",
            "    return self._sess_creator.create_session()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 878, in create_session\n",
            "    self.tf_sess = self._session_creator.create_session()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 638, in create_session\n",
            "    self._scaffold.finalize()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py\", line 3761, in _finalize\n",
            "    wrapped_finalize()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 237, in finalize\n",
            "    self._saver.build()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 840, in build\n",
            "    self._build(self._filename, build_save=True, build_restore=True)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 878, in _build\n",
            "    build_restore=build_restore)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 502, in _build_internal\n",
            "    restore_sequentially, reshape)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 381, in _AddShardedRestoreOps\n",
            "    name=\"restore_shard\"))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 328, in _AddRestoreOps\n",
            "    restore_sequentially)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 575, in bulk_restore\n",
            "    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_io_ops.py\", line 1696, in restore_v2\n",
            "    name=name)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py\", line 794, in _apply_op_helper\n",
            "    op_def=op_def)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py\", line 507, in new_func\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py\", line 3357, in create_op\n",
            "    attrs, op_def, compute_device)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py\", line 3426, in _create_op_internal\n",
            "    op_def=op_def)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py\", line 1748, in __init__\n",
            "    self._traceback = tf_stack.extract_stack()\n",
            "\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"object_detection/model_tpu_main.py\", line 142, in <module>\n",
            "    tf.app.run()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py\", line 40, in run\n",
            "    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/absl/app.py\", line 299, in run\n",
            "    _run_main(main, args)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/absl/app.py\", line 250, in _run_main\n",
            "    sys.exit(main(argv))\n",
            "  File \"object_detection/model_tpu_main.py\", line 126, in main\n",
            "    estimator.train(input_fn=train_input_fn, max_steps=train_steps)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py\", line 3035, in train\n",
            "    rendezvous.raise_errors()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py\", line 136, in raise_errors\n",
            "    six.reraise(typ, value, traceback)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/six.py\", line 693, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py\", line 3030, in train\n",
            "    saving_listeners=saving_listeners)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py\", line 370, in train\n",
            "    loss = self._train_model(input_fn, hooks, saving_listeners)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py\", line 1161, in _train_model\n",
            "    return self._train_model_default(input_fn, hooks, saving_listeners)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py\", line 1195, in _train_model_default\n",
            "    saving_listeners)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py\", line 1490, in _train_with_estimator_spec\n",
            "    log_step_count_steps=log_step_count_steps) as mon_sess:\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 584, in MonitoredTrainingSession\n",
            "    stop_grace_period_secs=stop_grace_period_secs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 1014, in __init__\n",
            "    stop_grace_period_secs=stop_grace_period_secs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 725, in __init__\n",
            "    self._sess = _RecoverableSession(self._coordinated_creator)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 1207, in __init__\n",
            "    _WrappedSession.__init__(self, self._create_session())\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 1212, in _create_session\n",
            "    return self._sess_creator.create_session()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 878, in create_session\n",
            "    self.tf_sess = self._session_creator.create_session()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 647, in create_session\n",
            "    init_fn=self._scaffold.init_fn)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/session_manager.py\", line 290, in prepare_session\n",
            "    config=config)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/session_manager.py\", line 220, in _restore_checkpoint\n",
            "    saver.restore(sess, ckpt.model_checkpoint_path)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 1326, in restore\n",
            "    err, \"a mismatch between the current graph and the graph\")\n",
            "tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:\n",
            "\n",
            "From /job:tpu_worker/replica:0/task:0:\n",
            "Unsuccessful TensorSliceReader constructor: Failed to get matching files on gs://staging.dreamer8090.appspot.com/tpu128/model.ckpt-60000: Permission denied: Error executing an HTTP request: HTTP response code 403 with body '{\n",
            "  \"error\": {\n",
            "    \"code\": 403,\n",
            "    \"message\": \"service-495559152420@cloud-tpu.iam.gserviceaccount.com does not have storage.objects.list access to staging.dreamer8090.appspot.com.\",\n",
            "    \"errors\": [\n",
            "      {\n",
            "        \"message\": \"service-495559152420@cloud-tpu.iam.gserviceaccount.com does not have storage.objects.list access to staging.dreamer8090.appspot.com.\",\n",
            "        \"domain\": \"global\",\n",
            "        \"reason\": \"forbidden\"\n",
            "      }\n",
            "    ]\n",
            "  }\n",
            "}\n",
            "'\n",
            "\t when reading gs://staging.dreamer8090.appspot.com/tpu128\n",
            "\t [[node save/RestoreV2 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]\n",
            "\n",
            "Original stack trace for 'save/RestoreV2':\n",
            "  File \"object_detection/model_tpu_main.py\", line 142, in <module>\n",
            "    tf.app.run()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py\", line 40, in run\n",
            "    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/absl/app.py\", line 299, in run\n",
            "    _run_main(main, args)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/absl/app.py\", line 250, in _run_main\n",
            "    sys.exit(main(argv))\n",
            "  File \"object_detection/model_tpu_main.py\", line 126, in main\n",
            "    estimator.train(input_fn=train_input_fn, max_steps=train_steps)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py\", line 3030, in train\n",
            "    saving_listeners=saving_listeners)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py\", line 370, in train\n",
            "    loss = self._train_model(input_fn, hooks, saving_listeners)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py\", line 1161, in _train_model\n",
            "    return self._train_model_default(input_fn, hooks, saving_listeners)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py\", line 1195, in _train_model_default\n",
            "    saving_listeners)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py\", line 1490, in _train_with_estimator_spec\n",
            "    log_step_count_steps=log_step_count_steps) as mon_sess:\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 584, in MonitoredTrainingSession\n",
            "    stop_grace_period_secs=stop_grace_period_secs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 1014, in __init__\n",
            "    stop_grace_period_secs=stop_grace_period_secs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 725, in __init__\n",
            "    self._sess = _RecoverableSession(self._coordinated_creator)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 1207, in __init__\n",
            "    _WrappedSession.__init__(self, self._create_session())\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 1212, in _create_session\n",
            "    return self._sess_creator.create_session()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 878, in create_session\n",
            "    self.tf_sess = self._session_creator.create_session()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 638, in create_session\n",
            "    self._scaffold.finalize()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py\", line 3761, in _finalize\n",
            "    wrapped_finalize()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py\", line 237, in finalize\n",
            "    self._saver.build()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 840, in build\n",
            "    self._build(self._filename, build_save=True, build_restore=True)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 878, in _build\n",
            "    build_restore=build_restore)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 502, in _build_internal\n",
            "    restore_sequentially, reshape)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 381, in _AddShardedRestoreOps\n",
            "    name=\"restore_shard\"))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 328, in _AddRestoreOps\n",
            "    restore_sequentially)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py\", line 575, in bulk_restore\n",
            "    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_io_ops.py\", line 1696, in restore_v2\n",
            "    name=name)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py\", line 794, in _apply_op_helper\n",
            "    op_def=op_def)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py\", line 507, in new_func\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py\", line 3357, in create_op\n",
            "    attrs, op_def, compute_device)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py\", line 3426, in _create_op_internal\n",
            "    op_def=op_def)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py\", line 1748, in __init__\n",
            "    self._traceback = tf_stack.extract_stack()\n",
            "\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "WPI_pOLj8mOt",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "\n",
        "# !export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim; python object_detection/model_tpu_main.py \\\n",
        "# --logtostderr \\\n",
        "# --pipeline_config_path=/content/drive/My Drive/tpu128.config \\\n",
        "# --model_dir=gs://mytf9133.appspot.com/train128 \\\n",
        "# --num_train_steps=200000 \\\n",
        "# --num_eval_steps=8000"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "ACO6RZcnq5O6",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "# !export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim; python object_detection/model_main.py \\\n",
        "# --logtostderr \\\n",
        "# --pipeline_config_path=data/gpu128.config \\\n",
        "# --model_dir=gpu128 \\\n",
        "# --num_train_steps=50000 \\\n",
        "# --num_eval_steps=8000"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "_RHNjNGxWXbM",
        "colab_type": "text"
      },
      "source": [
        "# 导出训练生成的文件"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "FmB8aDQ2fLUN",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "bucket_name=\"gs://staging.dreamer8090.appspot.com\"\n",
        "!gsutil cp  -r gs://staging.dreamer8090.appspot.com/tpu128  outdata/\n",
        "  \n",
        "# !gsutil cp  gs://{bucket_name}/data/pk_rmb.pbtxt A/\n",
        "  \n",
        "# !gsutil cp  gs://{bucket_name}/A/tflite_graph.pbtxt A/  "
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "6XYNLLWBMAAq",
        "colab_type": "text"
      },
      "source": [
        "# 导出能转换成tflte的pb"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "QCm2dKYrJg4_",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "!export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim; python object_detection/export_tflite_ssd_graph.py \\\n",
        "--pipeline_config_path=tpu128.config \\\n",
        "--trained_checkpoint_prefix=gs://staging.dreamer8090.appspot.com/data/tpu128/model.ckpt-50000 \\\n",
        "--output_directory=gs://staging.dreamer8090.appspot.com/outmodel/tpu128 \\\n",
        "--add_postprocessing_op=true"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "HRYvUkDLLIMC",
        "colab_type": "text"
      },
      "source": [
        "# 转换没有量化的tflite"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "MQKxRFI4W2e9",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "# !tflite_convert \\\n",
        "#   --graph_def_file=gs://mytf9133.appspot.com/train/output/tflite_graph.pb \\\n",
        "#   --input_format=TENSORFLOW_GRAPHDEF \\\n",
        "#   --output_format=TFLITE \\\n",
        "#   --output_file=gs://mytf9133.appspot.com/train/output/tflite_graph.tflite \\\n",
        "#   --inference_type=FLOAT \\\n",
        "#   --input_shapes=1,128,128,3 \\\n",
        "#   --input_arrays=normalized_input_image_tensor \\\n",
        "#   --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' \\\n",
        "#   --allow_custom_ops \\"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "Wgene9ty-w-d",
        "colab_type": "text"
      },
      "source": [
        "# 转换量化的tflite"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "3eiRYurJMkye",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 87
        },
        "outputId": "82d94b54-2deb-4294-f6ed-d2279ce8a714"
      },
      "source": [
        "!tflite_convert \\\n",
        "  --graph_def_file=/content/outmodel/tpu128/tflite_graph.pb \\\n",
        "  --output_format=TFLITE \\\n",
        "  --output_file=/content/outmodel/tpu128/tflite_graph.tflite \\\n",
        "  --input_arrays=normalized_input_image_tensor \\\n",
        "  --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' \\\n",
        "  --input_shapes=1,128,128,3 \\\n",
        "  --inference_type=QUANTIZED_UINT8 \\\n",
        "  --mean_value=128 \\\n",
        "  --std_dev_values=128 \\\n",
        "  --default_ranges_min=0 \\\n",
        "  --default_ranges_max=6 \\\n",
        "  --change_concat_input_ranges=false \\\n",
        "  --allow_custom_ops\n",
        " "
      ],
      "execution_count": 30,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "2019-10-31 03:36:18.691603: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz\n",
            "2019-10-31 03:36:18.691913: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x559c1229b640 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
            "2019-10-31 03:36:18.691953: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "0ZlhfY8aEeo2",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        ""
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "F0hqYCn-GgeO",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "%cd /content "
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "VOMgfFGD98nI",
        "colab_type": "text"
      },
      "source": [
        "# 下载模型到mytf4930工程 解压copy到gs://mytf_storage/data/"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "GF2OiFCISBFL",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "# cd /tmp\n",
        "# !curl -O http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18.tar.gz\n",
        "# !tar xzf ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18.tar.gz\n",
        "\n",
        "!gsutil cp -r ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18/  gs://lomasky8090_data/data/"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "dLnM6XuLfhkx",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "import os\n",
        "os.chdir(\"object_detection\")\n"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "deCTrT6FXpss",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "# !git clone https://github.com/skyloma/img2.git  \n",
        "!git clone https://github.com/tensorflow/models.git  \n",
        "  "
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "t0NpTGkaD2O6",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "!apt-get install protobuf-compiler python-pil python-lxml python-tk\n",
        "!pip install Cython\n",
        "\n",
        "#This creates a name_pb2.py file from every name.proto file in the \\object_detection\\protos folder.\n",
        "!cd models/research; protoc object_detection/protos/*.proto --python_out=."
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "t9S3eFJTfp52",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "!export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim; python xml_to_csv.py   --image_dir=/content/img2/"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "lTwrweg_YUhn",
        "colab_type": "text"
      },
      "source": [
        ""
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "4aGbmQTff3Pm",
        "colab_type": "code",
        "outputId": "176359c7-8de7-440d-c185-789a0c1957fc",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 34
        }
      },
      "source": [
        "%cd /content  \n",
        "import os\n",
        "os.chdir(\"models/research\")\n"
      ],
      "execution_count": 26,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "/content\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "KyBgWbLVmAxZ",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "!ls"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "4z9rXgFgfzSG",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "! export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim;python object_detection/generate_tfrecord52.py \\\n",
        "    --csv_input=/content/img2/train_labels.csv \\\n",
        "    --image_dir=/content/img2/train \\\n",
        "    --output_path=/content/train.record  \n",
        "# !  export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim; python object_detection/generate_tfrecord52.py \\\n",
        "#     --csv_input=/content/img2/test_labels.csv \\\n",
        "#     --image_dir=/content/img2/test \\\n",
        "#     --output_path=/content/test.record  "
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "VFl9cxUE_v_j",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        ""
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "cWcyNCFHpIg9",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        ""
      ],
      "execution_count": 0,
      "outputs": []
    }
  ]
}